USER seluser

COPY generate_config /opt/bin/generate_config

# Running this command as sudo just to avoid the message:
# To run a command as administrator (user "root"), use "sudo <command>". See "man sudo_root" for details.
# When logging into the container
RUN sudo echo ""

# Generating config inside the image rather than with entry_point.sh
RUN /opt/bin/generate_config > /opt/selenium/config.json

#====================================
# Scripts to run Selenium Standalone
#====================================
COPY entry_point.sh /opt/bin/entry_point.sh

EXPOSE 4444
